package:
  name: cantor
  version: 0.0.1

source:
  git_url: https://github.com/octakitten/cantor.git

requirements:
  build:
    - python
    - numpy
    - Pillow
    - Xlib
    - pytorch

  run:
    - python

test:
  imports:
    - cantor

about:
  home: https://github.com/octakitten/cantor
  license: GNU Affero Public License v3.0
  description: |
    Open-source Computer Behavior.