name: Python Package using Conda and Hatch

on: 
  push:
    branches:
      - main


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Configure conda-forge
      run: |
        conda config --add channels conda-forge
        conda config --set channel_priority strict
    - name: Install hatch
      run: |
        conda install -c conda-forge hatch
    - name: Install dependencies
      run: |
        hatch env create
        hatch shell
